---
title: Уравнение фильтрации и основные решения
bibliography: refs.bib
# указываем использовать названия глав в ссылка на рисунки, формулы, таблицы
crossref:
  chapters: true
# настройки html документа
format: 
  html:
    toc: true
    toc-depth: 1
    toc-expand: 2
    number-sections: true
    section-numbering: 1.1.1
    lang: ru
    embed-resources: true    # генерим один большой html файл    
    code-fold: true
    code-summary: "Показать код"

---

# Уравнение фильтрации
$$
\frac{\partial^2 p}{\partial r^2} + \frac{1}{r} \frac{\partial p}{\partial r}= \frac{\varphi \mu c_t}{k} \frac{\partial p}{\partial t}
$$ {#eq-diff_eq_lin}

## Безразмерные переменные

Часто для анализа уравнений неустановившейся фильтрации используются безразмерные переменные. Мы будем использовать переменные в виде:

$$ 
r_D = \frac{r}{r_w} 
$$

$$ 
t_D = \frac{kt}{\phi \mu c_t r_w^2}
$$

$$ 
p_D = \frac{2 \pi kh}{q_{ref} B \mu} \left( p_i - p \right) 
$$

$$ 
q_D =  \frac{q}{q_{ref}} 
$$

Здесь использованы единицы измерения СИ.

-   $r_w$ - радиус скважины, м
-   $r$ - расстояние от центра скважины до точки в пласте, м
-   $q_{ref}$ - референсный дебит скважины на поверхности, приведенный к нормальным условиям м^3^/с
-   $\phi$ - пористость, доли единиц
-   $\mu$ - вязкость нефти в пласте, Па с
-   $B$ - объемный коэффициент нефти, м^3^/м^3^
-   $p_i$ - начальное давление в пласте, Па
-   $p$ - давление забойное, Па
-   $c_t$ - общая сжимаемость системы в пласте, 1/Па
- $k$ - проницаемость, мД
- $t$ -  время, час

Использование безразмерных переменных позволяет упростить уравнение фильтрации, которое примет вид

$$ 
\frac{\partial p_D}{ \partial t_D} = \dfrac{1}{r_D} \left[ \dfrac{\partial}{\partial r_D} \left( r_D \dfrac{ \partial p_D} {\partial r_D} \right) \right] 
$$


# Формула Дюпюи и построение простых решений с python
Решение для задачи стационарного притока к вертикальной скважине в однородном изотропном пласте круговой формы с постоянным давлением на границе имеет вид

$$
q=\dfrac{2 \pi kh}{\mu B} \dfrac{P_{res}-P_{wf}}{\ln \dfrac{r_e}{r_w} + S} 
$$

$$
\ln \dfrac{r_e}{r_w} + S = \dfrac{2 \pi kh}{q\mu B} (P_{res}-P_{wf}) 
$$

$$
p_D = q_D (\ln r_{eD} + S)
$$

# граничное условие на скважине

$$
q = - 2 \pi r \frac{kh}{\mu}\frac{dp}{dr}
$$


$$
q_D = \left. r_D  \frac{d p_D}{d r_D} \right|_{r_D=1}
$$