# Начало {.unnumbered}


Планируется в книге собрать описания "простых" решений уравнения фильтрации которые можно использовать для решения практических задач с использованием python. 

Под простыми решениями (которые иногда оказываеются достаточно сложными) понимаются решения, которые смогут использовать студенты и специалисты интересующиеся вопросом имеющие базовые навыки использования python. Под простотой понимается возможность относительно простой реализации методов расчета решений в python или других язках программирования и относительно небольшие требования к ресурсам для проведения расчетов. Все должно неплохо работать на обычном ноутбуке или даже планшете где установлен python.

Также планируется дать для приведенных решений исчерпывающие теоретические описания включающие выводы всех используемых уравнений. А также привести достаточно подробные примеры расчетов иллюстрирующие некоторые вопросы практической реализации расчетов. Большинство расчетом направлены на построение графиков. Все расчеты можно воспроизвести.

Предполагается, что основное содержимое этой книги будет доступно в интернете в виде html страниц с использоваеним интерактивных элементов. Но бумажная версия тоже должна быть доступна с сувенирными и бюрократическими целями (хотя кому то, возможно, окажется полезна сама себе). Вряд ли в бумажной (pdf) версии получится сохранить что то интерактивное, также в бумажной (pdf) версии часть громозкого кода для построения графиков будет скрыта. В html версии такой код будет доступен в раскрывающихся листингах.

Наиболее полезные функции будут собраны в модуле `welltest.functions`, что позволит многократно их использовать. В перспективу эту библиотеку можно будет загрузить через стандартный менеджер пакетов python `pip`. Модуль также доступен в репозитории книги `welltest_examples`. 

